-- ============================================================================
-- 02_RAW_TABLES.SQL — Raw tables for Refinery Operations Intelligence
-- ============================================================================
USE DATABASE OIL_GAS_REFINERY;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.PROCESS_UNITS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SENSOR_READINGS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ALARM_HISTORY (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MAINTENANCE_LOG (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.OPERATIONS_DOCS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.REFINERY_ECONOMICS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

