-- Generated from generator/demo_specs/aws-malaysia-oil-gas-refinery.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-oil-gas-refinery
-- This is the schema that is actually deployed for MY_OIL_GAS_REFINERY.

-- Alerts fire on the bottom tail of Solomon EII
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_SOLOMON_EII) AS T
  FROM RAW.SENSOR_READINGS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_SOLOMON_EII <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_SOLOMON_EII), 2) AS AVG_SOLOMON_EII,
  ROUND(AVG(f.KPI_PRODUCT_YIELD), 2) AS AVG_PRODUCT_YIELD,
  ROUND(AVG(f.KPI_MARGIN_OPTIMIZATION), 2) AS AVG_MARGIN_OPTIMIZATION,
  ROUND(AVG(f.KPI_ENERGY_INDEX), 2) AS AVG_ENERGY_INDEX,
  ROUND(AVG(f.KPI_UNPLANNED_DOWNTIME), 2) AS AVG_UNPLANNED_DOWNTIME,
  ROUND(AVG(f.KPI_HYDROGEN_BALANCE), 2) AS AVG_HYDROGEN_BALANCE
FROM RAW.SENSOR_READINGS f
JOIN RAW.PROCESS_UNITS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_SOLOMON_EII), 2) AS AVG_SOLOMON_EII,
  ROUND(AVG(f.KPI_PRODUCT_YIELD), 2) AS AVG_PRODUCT_YIELD,
  ROUND(AVG(f.KPI_MARGIN_OPTIMIZATION), 2) AS AVG_MARGIN_OPTIMIZATION,
  ROUND(AVG(f.KPI_ENERGY_INDEX), 2) AS AVG_ENERGY_INDEX,
  ROUND(AVG(f.KPI_UNPLANNED_DOWNTIME), 2) AS AVG_UNPLANNED_DOWNTIME,
  ROUND(AVG(f.KPI_HYDROGEN_BALANCE), 2) AS AVG_HYDROGEN_BALANCE
FROM RAW.SENSOR_READINGS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SOLOMON_EII) AS KPI_SOLOMON_EII, AVG(KPI_UNPLANNED_DOWNTIME) AS KPI_UNPLANNED_DOWNTIME, AVG(KPI_PRODUCT_YIELD) AS KPI_PRODUCT_YIELD, AVG(KPI_MARGIN_OPTIMIZATION) AS KPI_MARGIN_OPTIMIZATION, AVG(KPI_ENERGY_INDEX) AS KPI_ENERGY_INDEX, AVG(KPI_HYDROGEN_BALANCE) AS KPI_HYDROGEN_BALANCE FROM RAW.SENSOR_READINGS),
     en AS (SELECT SUM(KPI_THROUGHPUT) AS KPI_THROUGHPUT FROM RAW.PROCESS_UNITS)
  SELECT 1 AS SORT_ORDER, 'Throughput' AS TITLE, KPI_THROUGHPUT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_THROUGHPUT) / 1000)) AS DECIMAL(38,0))) || 'K' || ' ' || 'bpd' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Solomon EII' AS TITLE, KPI_SOLOMON_EII AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SOLOMON_EII), 1) AS DECIMAL(38,1))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Unplanned Downtime' AS TITLE, KPI_UNPLANNED_DOWNTIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_UNPLANNED_DOWNTIME), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Product Yield' AS TITLE, KPI_PRODUCT_YIELD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PRODUCT_YIELD)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Margin Optimization' AS TITLE, KPI_MARGIN_OPTIMIZATION AS VALUE_NUM, '+' || 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_MARGIN_OPTIMIZATION) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || '/day' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Energy Index' AS TITLE, KPI_ENERGY_INDEX AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ENERGY_INDEX)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Hydrogen Balance' AS TITLE, KPI_HYDROGEN_BALANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_HYDROGEN_BALANCE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
