-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Refinery Operations Intelligence
-- ============================================================================
USE DATABASE OIL_GAS_REFINERY;
USE SCHEMA ML;

-- ML.ANOMALY_DETECTION: PROCESS_EXCURSION_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.PROCESS_EXCURSION_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SENSOR_TIMESERIES'),
  SERIES_COLNAME => 'UNIT_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.PROCESS_EXCURSION_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.PROCESS_EXCURSION_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SENSOR_TIMESERIES'), SERIES_COLNAME => 'UNIT_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

-- ML.FORECAST: THROUGHPUT_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.THROUGHPUT_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.THROUGHPUT_ECONOMICS'),
  SERIES_COLNAME => 'UNIT_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.THROUGHPUT_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.THROUGHPUT_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

