-- ============================================================================
-- 99_RESET.SQL — Reset Refinery Operations Intelligence to clean demo state
-- ============================================================================
USE DATABASE OIL_GAS_REFINERY;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_ANOMALY_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SEND_NOTIFICATIONS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.UNIT_AVAILABILITY REFRESH;
ALTER DYNAMIC TABLE CURATED.SENSOR_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.ALARM_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.THROUGHPUT_ECONOMICS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM OIL_GAS_REFINERY.RAW.SENSOR_READINGS → 2000000
-- SELECT COUNT(*) FROM OIL_GAS_REFINERY.RAW.ALARM_HISTORY → 5000
-- SELECT COUNT(*) FROM OIL_GAS_REFINERY.CURATED.UNIT_AVAILABILITY WHERE AVAILABILITY_PCT < 0.95 → >=1

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_SEND_NOTIFICATIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_ANOMALY_MODELS RESUME;
